import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  documentationSidebar: [
    {
      type: "category",
      label: "Overview",
      collapsed: false,
      items: [
        "what-is-yivi",
        "getting-started",
        "technical-overview",
        "yivi-app",
      ],
    },
    {
      type: "category",
      label: "Concepts",
      collapsed: false,
      items: [
        "irma-cli",
        "irma-server",
        "irma-server-lib",
        "irma-backend",
        "yivi-frontend",
        "schemes",
        "issuer",
        "session-requests",
        "condiscon",
        "email",
        "stateless",
        "revocation",
        "randomblind",
        "chained-sessions",
        "trusted-verifier",
      ],
    },
    {
      type: "category",
      label: "API reference",
      collapsed: false,
      items: ["api-go", "api-irma-server", "api-yivi-frontend"],
    },
    {
      type: "category",
      label: "Background",
      collapsed: false,
      items: ["irma-protocol", "zkp", "keyshare-protocol"],
    },
    {
      type: "category",
      label: "EUDI",
      collapsed: false,
      items: ["sdjwtvc-issuance"],
    },
  ],
};

export default sidebars;
