FROM node:20-alpine AS base
WORKDIR /app
COPY yivi-docs/package*.json ./
RUN npm ci

# ----------------------

FROM base AS dev
WORKDIR /app
COPY yivi-docs/. .
EXPOSE 3000

ENV HOST=0.0.0.0 \
    PORT=3000 \
    CHOKIDAR_USEPOLLING=true \
    WATCHPACK_POLLING=true

CMD ["npm", "run", "start", "--", "--host", "0.0.0.0", "--port", "3000"]
