@startuml session-pairing
skinparam sequence {
backgroundColor #transparent
ActorBorderColor #7A2626
ActorBackgroundColor #transparent
ParticipantBorderColor #7A2626
ParticipantBackgroundColor #004C92
ParticipantFontColor white
} 

actor "IRMA app user" as user
participant "IRMA app" as app
participant frontend as browser
participant "requestor" as requestor
participant "IRMA server" as server


user -> browser: initiate session
browser -> requestor: <font color=#1D5B2A>**POST** /session/</font> (create session)
requestor -> server: initiate session
server <- server: set state to INITIALIZED
server --> requestor: session pointer + requestor token + frontendAuth 
requestor --> browser: session pointer (QR) + frontendAuth
browser -> server: <font color=#1D5B2A>**POST** /irma/session/{clientToken}/frontend/options</font> (enable pairing)
return pairingCode
browser -> server: <font color=#1D5B2A>**GET** /irma/session/{clientToken}/frontend/status </font>(start polling)
browser -> user: QR
user -> app: scan QR
app -> browser: read QR
app -> server: <font color=#1D5B2A>**GET** /irma/session/{clientToken}</font>
' if pairing is not enabled, the session request will be returned directly
return pairing method and code
app -> user: pairing code
server <- server: change state to PAIRING
server --> browser: polling response: state changed to PAIRING
app -> server: <font color=#1D5B2A>**GET** /irma/session/{clientToken}/status</font> (start polling)
browser -> user: pairing code?
return pairing code
browser -> server: <font color=#1D5B2A>**POST** /irma/session/{clientToken}/frontend/pairingcompleted</font>
server <- server: change state to CONNECTED
server --> browser: polling response: state changed to CONNECTED
server --> app: polling response: state changed to CONNECTED

app -> server: <font color=#1D5B2A>**GET** /irma/session/{clientToken}/request</font>
return session request
app -> user: perform session?
return yes

app -> server: <font color=#1D5B2A>**POST** /irma/session/{clientToken}/proofs or /irma/session/{clientToken}/commitments</font>
return proofStatus, possibly nextSession, possibly issuer signatures
server <- server: change state to DONE

server --> browser: polling response: state changed to DONE (+ possibly nextSession)
browser -> requestor: done
requestor -> server: <font color=#1D5B2A>**GET** /session/{requestorToken}/result
server -> requestor: session result
requestor --> browser: follow-up action

browser -> user: follow-up action

@enduml
